name: Deploy to Vultr

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login "https://sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }}" -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.APP_NAME }}:latest . --no-cache
        docker tag ${{ secrets.APP_NAME }}:latest sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.APP_NAME }}:latest
        docker push sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.APP_NAME }}:latest

    - name: Deploy to Vultr
      run: |
        echo "${{ secrets.VULTR_SERVER_SSH_KEY }}" > /tmp/vultr_key
        
        # Ensure the key has the correct permissions
        chmod 600 /tmp/vultr_key
        
        # Connect to the server
        ssh -o StrictHostKeyChecking=no -i /tmp/vultr_key ${{ secrets.VULTR_SERVER_USER }}@${{ secrets.VULTR_SERVER_IP }} << 'EOF'

          # Volumes configuration
          mkdir -p ${{ secrets.BOT_NAME }}
          
          # Clear previous containers
          docker stop ${{ secrets.APP_NAME }} || true
          docker rm ${{ secrets.APP_NAME }} || true
   
          # Run the container
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login https://sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }} -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          
          docker pull sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.APP_NAME }}:latest
          
          docker run -d --name ${{ secrets.APP_NAME }} \
          --network my-network \
          -v /${{ secrets.VULTR_SERVER_USER }}/${{ secrets.BOT_NAME }}:/usr/src/app/data \
          -v /${{ secrets.VULTR_SERVER_USER }}/nginx/ssl:/usr/src/app/ssl \
          -e BOT_NAME=${{ secrets.BOT_NAME }} \
          -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          -e MY_ID=${{ secrets.MY_ID }} \
          -e WEBHOOK_URL=${{ secrets.WEBHOOK_URL }} \
          -e SECRET_TOKEN=${{ secrets.SECRET_TOKEN }} \
          -e CERT_FILE_PATH=./ssl/selfsigned.pem \
          sjc.vultrcr.com/${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.APP_NAME }}:latest

          # Clear unused
          docker system prune -af 
        EOF

    - name: Clean up temporary files
      run: |
        rm -f /tmp/vultr_key
